export const ActionTypes = {
  // Assistants
  FETCH_ASSISTANTS: 'FETCH_ASSISTANTS',
  SET_ASSISTANTS: 'SET_ASSISTANTS',
  SELECTED_ASSISTANT: 'SELECTED_ASSISTANT',
  REMOVE_SELECTED_ASSISTANT: 'REMOVE_SELECTED_ASSISTANT',
  // Schedule
  FETCH_SCHEDULERS: 'FETCH_SCHEDULERS',
  SET_SCHEDULER: 'SET_SCHEDULER',
  // Auth
  FAILED_REQUEST: 'AUTH_FAILED_REQUEST',
  LOADING_REQUEST: 'AUTH_LOADING_REQUEST',
  LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'AUTH_LOGOUT_SUCCESS'
}
